/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package edu.my.myquanlysinhvie.ui;

import javax.swing.ImageIcon;

/**
 *
 * @author Laptop T&T
 */
public class MainForm extends javax.swing.JFrame {
    private StudentManagementPanal mStudentPanel;
    private GPAManagementPanel mGPAPanel;
    /**
     * Creates new form MainForm
     */
    public MainForm() {
        initComponents();
        
        setLocationRelativeTo(null);//canh giua man hinh
        
        //setExtendedState(getExtendedState()| JFrame.MAXIMIZED BOTH);
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator2 = new javax.swing.JSeparator();
        jToolBar1 = new javax.swing.JToolBar();
        tbrLogout = new javax.swing.JButton();
        jSeparator4 = new javax.swing.JToolBar.Separator();
        mnuManagerStu = new javax.swing.JButton();
        jSeparator5 = new javax.swing.JToolBar.Separator();
        nmuManagerPoi = new javax.swing.JButton();
        jSeparator6 = new javax.swing.JToolBar.Separator();
        tbrAbourUs = new javax.swing.JButton();
        tplMainBoard = new javax.swing.JTabbedPane();
        jLabel2 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        mnuFile_Exit = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        mnuManageStudent = new javax.swing.JMenuItem();
        mnuManageGPA = new javax.swing.JMenuItem();
        mnuAboutAs = new javax.swing.JMenu();
        jMenuItem5 = new javax.swing.JMenuItem();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        jMenuItem6 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jToolBar1.setRollover(true);

        tbrLogout.setBackground(new java.awt.Color(204, 204, 255));
        tbrLogout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/my/myquanlysinhvie/icons/iconset4/logout-icon-32.png"))); // NOI18N
        tbrLogout.setText("Log out");
        tbrLogout.setFocusable(false);
        tbrLogout.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        tbrLogout.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        tbrLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbrLogoutActionPerformed(evt);
            }
        });
        jToolBar1.add(tbrLogout);
        jToolBar1.add(jSeparator4);

        mnuManagerStu.setBackground(new java.awt.Color(204, 204, 255));
        mnuManagerStu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/my/myquanlysinhvie/icons/iconset4/10207-man-student-light-skin-tone-icon-32 - Copy (2) - Copy.png"))); // NOI18N
        mnuManagerStu.setText("Manager Student");
        mnuManagerStu.setFocusable(false);
        mnuManagerStu.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        mnuManagerStu.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        mnuManagerStu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuManagerStuActionPerformed(evt);
            }
        });
        jToolBar1.add(mnuManagerStu);
        jToolBar1.add(jSeparator5);

        nmuManagerPoi.setBackground(new java.awt.Color(204, 204, 255));
        nmuManagerPoi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/my/myquanlysinhvie/icons/iconset4/gpa-icon-32.png"))); // NOI18N
        nmuManagerPoi.setText("Manager point");
        nmuManagerPoi.setFocusable(false);
        nmuManagerPoi.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        nmuManagerPoi.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        nmuManagerPoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nmuManagerPoiActionPerformed(evt);
            }
        });
        jToolBar1.add(nmuManagerPoi);
        jToolBar1.add(jSeparator6);

        tbrAbourUs.setBackground(new java.awt.Color(204, 204, 255));
        tbrAbourUs.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/my/myquanlysinhvie/icons/iconset4/Actions-help-about-icon-32.png"))); // NOI18N
        tbrAbourUs.setText("Information");
        tbrAbourUs.setFocusable(false);
        tbrAbourUs.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        tbrAbourUs.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        tbrAbourUs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbrAbourUsActionPerformed(evt);
            }
        });
        jToolBar1.add(tbrAbourUs);

        jLabel2.setForeground(new java.awt.Color(153, 0, 0));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/my/myquanlysinhvie/icons/iconset4/truongcuoi.jpg"))); // NOI18N
        tplMainBoard.addTab("", jLabel2);

        jMenuBar1.setBackground(new java.awt.Color(153, 0, 0));
        jMenuBar1.setForeground(new java.awt.Color(102, 0, 0));

        jMenu1.setText("System");

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_U, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMenuItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/my/myquanlysinhvie/icons/iconset4/Login-icon-16.png"))); // NOI18N
        jMenuItem1.setText("Log out");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);
        jMenu1.add(jSeparator1);

        mnuFile_Exit.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_X, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        mnuFile_Exit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/my/myquanlysinhvie/icons/iconset4/Actions-edit-delete-icon-16 - Copy.png"))); // NOI18N
        mnuFile_Exit.setText("Exit");
        mnuFile_Exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuFile_ExitActionPerformed(evt);
            }
        });
        jMenu1.add(mnuFile_Exit);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Manager");

        mnuManageStudent.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_T, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        mnuManageStudent.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/my/myquanlysinhvie/icons/iconset4/10207-man-student-light-skin-tone-icon-16 - Copy - Copy - Copy (3).png"))); // NOI18N
        mnuManageStudent.setText("Manager Student");
        mnuManageStudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuManageStudentActionPerformed(evt);
            }
        });
        jMenu2.add(mnuManageStudent);

        mnuManageGPA.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/my/myquanlysinhvie/icons/iconset4/Actions-document-edit-icon-16 - Copy - Copy (4).png"))); // NOI18N
        mnuManageGPA.setText("Manager Point");
        mnuManageGPA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuManageGPAActionPerformed(evt);
            }
        });
        jMenu2.add(mnuManageGPA);

        jMenuBar1.add(jMenu2);

        mnuAboutAs.setText("Help");
        mnuAboutAs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuAboutAsActionPerformed(evt);
            }
        });

        jMenuItem5.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F1, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMenuItem5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/my/myquanlysinhvie/icons/iconset4/Help-icon-16.png"))); // NOI18N
        jMenuItem5.setText("Introduction");
        mnuAboutAs.add(jMenuItem5);
        mnuAboutAs.add(jSeparator3);

        jMenuItem6.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F1, 0));
        jMenuItem6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/my/myquanlysinhvie/icons/iconset4/Actions-help-about-icon-16.png"))); // NOI18N
        jMenuItem6.setText("Content");
        mnuAboutAs.add(jMenuItem6);

        jMenuBar1.add(mnuAboutAs);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tplMainBoard)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tplMainBoard, javax.swing.GroupLayout.PREFERRED_SIZE, 583, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(63, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void mnuManageGPAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuManageGPAActionPerformed
        if(mGPAPanel == null){
            mGPAPanel = new GPAManagementPanel();
            ImageIcon icon = new ImageIcon(getClass()
                .getResource("/edu/my/myquanlysinhvie/icons/iconset4/gpa-icon.png"));
            tplMainBoard.addTab("Quản lý điểm", icon, mGPAPanel, "Quản lý sinh điểm");
        }
        tplMainBoard.setSelectedComponent(mGPAPanel);
    }//GEN-LAST:event_mnuManageGPAActionPerformed

    private void tbrAbourUsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbrAbourUsActionPerformed
        AboutUsDialog aboutDialog = new AboutUsDialog(this, true);
        aboutDialog.setVisible(true);
    }//GEN-LAST:event_tbrAbourUsActionPerformed

    private void mnuFile_ExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuFile_ExitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_mnuFile_ExitActionPerformed

    private void mnuManageStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuManageStudentActionPerformed
        if(mStudentPanel == null){//neu doi tuong chua tạo sẽ tao con tao roi thi hien thi khong them nua          
            mStudentPanel= new StudentManagementPanal();
            ImageIcon icon = new ImageIcon(getClass()
                .getResource("/edu/my/myquanlysinhvie/icons/iconset4/10207-man-student-light-skin-tone-icon-16.png"));
            tplMainBoard.addTab("Quản lý sinh viên", icon, mStudentPanel, "Quản lý sinh viên");
        }
        tplMainBoard.setSelectedComponent(mStudentPanel);
    }//GEN-LAST:event_mnuManageStudentActionPerformed

    private void mnuAboutAsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuAboutAsActionPerformed
        tbrAbourUsActionPerformed(evt);
    }//GEN-LAST:event_mnuAboutAsActionPerformed

    private void tbrLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbrLogoutActionPerformed
        LoginDialog loginDialog = new LoginDialog(this, true);
        loginDialog.setVisible(true);
    }//GEN-LAST:event_tbrLogoutActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        LoginDialog dialog = new LoginDialog(this, true);
        dialog.setVisible(true);
    }//GEN-LAST:event_formWindowOpened

    private void mnuManagerStuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuManagerStuActionPerformed
         if(mStudentPanel == null){//neu doi tuong chua tạo sẽ tao con tao roi thi hien thi khong them nua          
            mStudentPanel= new StudentManagementPanal();
            ImageIcon icon = new ImageIcon(getClass()
                .getResource("/edu/my/myquanlysinhvie/icons/iconset4/10207-man-student-light-skin-tone-icon-16.png"));
            tplMainBoard.addTab("Quản lý sinh viên", icon, mStudentPanel, "Quản lý sinh viên");
        }
        tplMainBoard.setSelectedComponent(mStudentPanel);
    }//GEN-LAST:event_mnuManagerStuActionPerformed

    private void nmuManagerPoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nmuManagerPoiActionPerformed
         if(mGPAPanel == null){
            mGPAPanel = new GPAManagementPanel();
            ImageIcon icon = new ImageIcon(getClass()
                .getResource("/edu/my/myquanlysinhvie/icons/iconset4/gpa-icon.png"));
            tplMainBoard.addTab("Quản lý điểm", icon, mGPAPanel, "Quản lý sinh điểm");
        }
        tplMainBoard.setSelectedComponent(mGPAPanel);
    }//GEN-LAST:event_nmuManagerPoiActionPerformed
    
   
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    private javax.swing.JToolBar.Separator jSeparator4;
    private javax.swing.JToolBar.Separator jSeparator5;
    private javax.swing.JToolBar.Separator jSeparator6;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JMenu mnuAboutAs;
    private javax.swing.JMenuItem mnuFile_Exit;
    private javax.swing.JMenuItem mnuManageGPA;
    private javax.swing.JMenuItem mnuManageStudent;
    private javax.swing.JButton mnuManagerStu;
    private javax.swing.JButton nmuManagerPoi;
    private javax.swing.JButton tbrAbourUs;
    private javax.swing.JButton tbrLogout;
    private javax.swing.JTabbedPane tplMainBoard;
    // End of variables declaration//GEN-END:variables
}
